### ISSUE TITLE
W1050 WideChar reduced to byte char in set expressions

### ISSUE THREAD

**Issue by Ravaut123** [ezequieljuliano/SQLBuilder4Delphi#3]
I'm use Delphi Tokyo 10.2 and I get some warnings:

[dcc32 Warning] gaBasicSQLParser.pas(357): W1050 WideChar reduced to byte char in set expressions.  Consider using 'CharInSet' function in 'SysUtils' unit.

I've change
`if (FCurrentPos+1)^ in ['*', '/'] then`
into
`if CharInSet((FCurrentPos+1)^, ['*', '/']) then`

Is it possible to update the code?

**Comment by ezequieljuliano** [comment]
Correction effected.
